handlers = java.util.logging.FileHandler

.level = INFO
budgethanteraren.level = FINE

java.util.logging.FileHandler.pattern = logs/budgethanteraren.log
java.util.logging.FileHandler.level = FINE
java.util.logging.FileHandler.formatter = java.util.logging.SimpleFormatter
java.util.logging.FileHandler.append = true

java.util.logging.SimpleFormatter.format = %1$tF %1$tT %4$-7s [%3$s] %5$s%n